[project]
name = "pythonproject12"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas (>=3.0.5,<4.0.0)",
    "path (>=17.1.1,<18.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "pulp (>=3.3.2,<4.0.0)",
    "plt (>=0.2.0,<0.3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
